### ISSUE TITLE
update Google Cloud API client import paths and more

### ISSUE THREAD

**Issue by jba** [rainchasers/com.rainchasers.gauge#1]
The Google Cloud API client libraries for Go are making some breaking changes:
- The import paths are changing from `google.golang.org/cloud/...` to
  `cloud.google.com/go/...`. For example, if your code imports the BigQuery client
  it currently reads
  `import "google.golang.org/cloud/bigquery"`
  It should be changed to
  `import "cloud.google.com/go/bigquery"`
- Client options are also moving, from `google.golang.org/cloud` to
  `google.golang.org/api/option`. Two have also been renamed:
  - `WithBaseGRPC` is now `WithGRPCConn`
  - `WithBaseHTTP` is now `WithHTTPClient`
- The `cloud.WithContext` and `cloud.NewContext` methods are gone, as are the
  deprecated pubsub and container functions that required them. Use the `Client`
  methods of these packages instead.

You should make these changes before September 12, 2016, when the packages at
`google.golang.org/cloud` will go away.

**Comment by robtuley** [comment]
Forgot to close this (thanks for the direct issue headsup btw). Fixed in commit ad7730359144a31c3b6c824bcb6ef1f8d55fa8fd the `/bigquery/` looks like it still uses the older API but that app is current deprecated pending a larger refactor.
